---
- name : Hello World!
  hosts: vsrx1
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

 
  tasks:
#    - debug:
#      msg: "I am connecting to {{ ansible_nodename }} "

    - name: Checking NETCONF connectivity
      wait_for: host={{ inventory_hostname }} port=830 timeout=5
 
    - name: Get Junos device information
      junos_get_facts:
       host={{ inventory_hostname }}
      register: junos
 
    - name: Print Junos facts
      debug: msg="{{ junos.facts }}"
 
#    - name: collect interface information using rpc
#      junos_rpc:
#      rpc: get-interface-information
#      args:
#       interface-name: fxp0
#       media: True
# 
#    - name: get system information
#      junos_rpc:
#       host={{ inventory_hostname }}
#      rpc: "get-system-information"